version: '3'

services:
  proxy:
    image: balletrafaelaguilar/playground-proxy:1.0.0
    ports:
      - "443:443"

  user:
    image: balletrafaelaguilar/user-service:1.0.0
    environment:
      - NODE_ENV=docker
    ports:
      - "3333:3333"

  playground:
    image: balletrafaelaguilar/dance-show-playground:1.0.0
    ports:
      - "4000:4000"
